services:
  - type: web
    name: goobapp-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_KEY
        value: ""
      - key: PORT
        value: 10000
